export const ORDER_SET_FORM = 'ORDER_SET_FORM'
export const ORDER_CLEAR_FORM = 'ORDER_CLEAR_FORM'
export const ORDER_SET_ORDER = 'ORDER_SET_ORDER'
export const ORDER_CREATE_ORDER = 'ORDER_SET_CREATE_RESOURCE'
