// export const USER_ACCOUNT_INFO_REQUEST_BEGIN = 'USER_ACCOUNT_INFO_REQUEST_BEGIN'
// export const USER_ACCOUNT_INFO_REQUEST_SUCCESS = 'USER_ACCOUNT_INFO_REQUEST_SUCCESS'
// export const USER_ACCOUNT_INFO_REQUEST_FAILURE = 'USER_ACCOUNT_INFO_REQUEST_FAILURE'

export const USER_ACCOUNT_LOGIN = 'USER_ACCOUNT_LOGIN'